### ISSUE TITLE
Change default configuration directory

### ISSUE THREAD

**Issue by fbetil** [MaxBelkov/visualsyslog#10]
Hi,
Actually, i'm unable to change the default configuration directory.
I want to store filter.xml, params.ini elsewhere (ie: in the program folder, ..)
Thanks,
Florian

**Comment by MaxBelkov** [comment]
Hi.
Just use ntfs folder symbolic link (https://en.wikipedia.org/wiki/NTFS_symbolic_link):
1) Exit Visual Syslog Server
2) Move C:\Users\<your user name>\AppData\Local\visualsyslog to c:\visualsyslog (for example)
3) Run command: mklink /d C:\Users\<your user name>\AppData\Local\visualsyslog C:\visualsyslog
4) Start Visual Syslog Server and enjoy :)
